### ISSUE TITLE
A few questions + Example issues

### ISSUE THREAD

**Issue by gadu** [LeonardoCardoso/SwiftLinkPreview#15]
Hello,
Currently your example project seems to rely on 3 pods, but I was only able to find that out by looking at the readme file on that directory. It would be a lot easier if you provided a pod file, did basic integration with cocoa pods and then provided an .xcworkspace that people could use to run the sample project out the box.

Also, i noticed you pushed a release removing the dependency on Alamofire, but the sample code still requires a pod that deals with alamofire and use it (for example: `if let source: AlamofireSource = AlamofireSource(urlString: image) {` on `ViewController.swift:125`).

I've noticed that you have been very active recently on this project though so I'm just assuming it's still a work in progress. I am very interested in using this in a project I am working on but because you are in the process of making changes I wanted to ask you your opinions first.

Seeing as you are in currently making changes, is it at a place where it would be ok to integrate now and update as you make changes, or are there things you are getting to or want to check out first? We are getting very close to testing the app for a production release, and want to get a sense if we should delay integration for a few days/a week until its a little more stable?

P.S.: It's on obj-c project and some of my pods don't play nicely together with use_frameworks! so i'd have to manually integrate it, which is why I ask

**Comment by LeonardoCardoso** [comment]
@gadu Hi. First of all thanks. I assumed that it would be safe only after I wrote down the tests. And it's been done recently. You can consider the current version as stable then. 

Regarding the Example, I provided it without a specific dependency manager on purpose because SLP does not rely only on CocoaPods and the users can simply add those libraries as they want, that's why the README.md.

The example itself only shows visually what the lib can do. So how you will display the data is up to you. I used Alamofire on the example alone, it was previously on the library doing another work. You gotta have in mind that the [library work is to deliver the dictionary data to you](https://github.com/LeonardoCardoso/SwiftLinkPreview#usage).

**Comment by gadu** [comment]
Great. That makes sense, not entirely sure what Alamofire does so would she
helped to look into it before, just didn't want an unneeded dependency.

So just to confirm then, you're not in the process of working on something
that will improve this solution then or about to push something worth
waiting for?

And yes this is a great project, started to do something similar but really
glad I found this since the regex and crawling accomplishes something I was
sure was going to be a major headache in my implementation! Thanks again

**Comment by LeonardoCardoso** [comment]
`Alamofire` was helping to get the real URL of an shorten URL, but it was dispensable because `NSURLSession` allows us to do the same.

The current code is stable and you can use on your project.

Thanks. You can close the issue if you don't have any questions else.

**Comment by gadu** [comment]
Yep, thanks for speedy response and great project
