### ISSUE TITLE
Broken stuff?

### ISSUE THREAD

**Issue by davidseek** [LeonardoCardoso/SwiftLinkPreview#34]
I'm lately trying to stay away from Pods. That's why I've wanted to download your project manually. `You just need to drop SwiftLinkPreview folder into Xcode project (make sure to enable "Copy items if needed" and "Create groups").` There is no folder `SwiftLinkPreview`.

Also the Example Project is kinda empty. No `SwiftLinkPreview` files and doesn't build at all. I thought about missing `pod install`, but a podfile is missing also.

**Comment by LeonardoCardoso** [comment]
Hi @davidseek!

You are right about the ` SwiftLinkPreview folder`. Thanks for letting me know. This part was written before I port SLP to SPM. I'll fix that.

And have you read the [Example's README.md](https://github.com/LeonardoCardoso/SwiftLinkPreview/blob/master/Example/README.md)? Since my project doesn't support only CocoaPods, but Carthage too, for instance, I preferred to leave the decision for the user (him/her)self to install it as wish. The issue on Example is that if you added SLP via drag and drop, the `*.plists` files would conflict. I'll also fix the Example issue too.

If you wanna try with `pod`, please create this `Podfile`:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftLinkPreviewExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftLinkPreviewExample

  pod 'Alamofire'
  pod 'SwiftyDrop'
  pod 'ImageSlideshow', '~> 1.0.0-beta.1'
  pod 'ImageSlideshow/Alamofire'

end
```
