### ISSUE TITLE
link-preview response  is different in iOS & Android 

### ISSUE THREAD

**Issue by SurenderBDAppManiac** [LeonardoCardoso/SwiftLinkPreview#87]
hello,
I am using swiftLinkPreview githup in my iOS app, actually issue is i'm share LinkedIn user profile into my app and extract this url with swiftLinkPreView Framework and i'm getting response different from android phone.... can u explain me what is issue related to linkedin profile extract i am getting this:
Title - linkedIn Login & SignUp
desc - 
imageUrl - nil
but i'm logged in with LinkedIn account in my iPhone

i want to know why the link-preview response  is different in iOS & Android.. or any thing privacy with ios

**Comment by LeonardoCardoso** [comment]
My lib does not watch sessions. And to see a LinkedIn profile, you must be logged. That's why.
And are you talking about my other repository [https://github.com/LeonardoCardoso/Android-Link-Preview](https://github.com/LeonardoCardoso/Android-Link-Preview)? I haven't touched that code in ages. I have no plans to either.
